let config = {
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNha2FtYW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwidXNlcklkIjoiNWE3YjgyNDdkMjQzZDI1NTU3YmQyOWYyIiwiaWF0IjoxNTE5MTUzOTk3LCJleHAiOjE1MTkxNjExOTd9.3xtQCXmDM7MMP10ezBb3-J6kAXGLOvWuWnWSoZUjZGg"
}

module.exports = config;